#include "runtime/log/symcache.h"

#include <cstdlib>
#include <cstring>
#include <vector>

namespace evr {

// ---------------------------------------------------------------------------
// Embedded symbol cache data (generated by tools/generate-symcache.sh)
// ---------------------------------------------------------------------------

// Defined in the auto-generated symcache_data.cpp
extern const SymCacheEntry kSymCacheData[];
extern const int kSymCacheCount;

// ---------------------------------------------------------------------------
// Runtime cache
// ---------------------------------------------------------------------------

static std::unordered_map<uint64_t, std::string> s_symbols;
static bool s_loaded = false;

void InitSymbolCache() {
    if (s_loaded) return;

    s_symbols.reserve(static_cast<size_t>(kSymCacheCount));
    for (int i = 0; i < kSymCacheCount; ++i) {
        s_symbols[kSymCacheData[i].hash] = kSymCacheData[i].name;
    }
    s_loaded = true;
}

// ---------------------------------------------------------------------------
// Hash resolution — manual scan (no <regex>; that header is heavy on MinGW)
// ---------------------------------------------------------------------------

// Returns true if c is a hex digit [0-9a-fA-F].
static inline bool IsHexDigit(char c) {
    return (c >= '0' && c <= '9')
        || (c >= 'a' && c <= 'f')
        || (c >= 'A' && c <= 'F');
}

// Parse exactly 16 hex digits from s starting at i into *out.
// Returns true on success, false if fewer than 16 hex digits available.
static bool ParseHex16(const char* s, size_t start, size_t len, uint64_t* out) {
    if (start + 16 > len) return false;
    uint64_t v = 0;
    for (int k = 0; k < 16; ++k) {
        char c = s[start + k];
        if (!IsHexDigit(c)) return false;
        v <<= 4;
        if (c >= '0' && c <= '9')      v |= static_cast<uint64_t>(c - '0');
        else if (c >= 'a' && c <= 'f')  v |= static_cast<uint64_t>(c - 'a' + 10);
        else                            v |= static_cast<uint64_t>(c - 'A' + 10);
    }
    *out = v;
    return true;
}

std::string ResolveSymbolHashes(const std::string& line) {
    if (!s_loaded || line.empty()) return line;

    const char* s = line.data();
    const size_t len = line.size();

    // Collect replacement ranges: [start, end) -> replacement string.
    // Process left-to-right so indices stay valid.
    struct Replacement {
        size_t start;
        size_t end;
        std::string value;
    };
    std::vector<Replacement> replacements;
    replacements.reserve(16);  // typical line has few hashes, if any

    for (size_t i = 0; i + 17 < len; ++i) {
        // Look for "0x" prefix followed by exactly 16 hex digits.
        // We require the prefix "0x" (two chars), then 16 hex digits.
        // The total pattern is 18 chars: 0xXXXXXXXXXXXXXXXX
        if (s[i] == '0' && (s[i + 1] == 'x' || s[i + 1] == 'X')) {
            uint64_t hash = 0;
            if (ParseHex16(s, i + 2, len, &hash)) {
                auto it = s_symbols.find(hash);
                if (it != s_symbols.end()) {
                    replacements.push_back({i, i + 18, it->second});
                    i += 17;  // skip past the 18-char hash (loop ++i adds 1)
                }
                // Unknown hashes pass through unchanged — no replacement.
            }
        }
    }

    if (replacements.empty()) return line;

    // Build the output with replacements
    std::string result;
    result.reserve(line.size() + replacements.size() * 16);  // generous estimate
    size_t pos = 0;
    for (const auto& r : replacements) {
        result.append(s + pos, r.start - pos);
        result.append(r.value);
        pos = r.end;
    }
    result.append(s + pos, len - pos);
    return result;
}

std::string AnnotateGameLine(const std::string& line) {
    std::string result;
    result.reserve(line.size() + 64);
    result = "[EVR] ";
    result += ResolveSymbolHashes(line);
    return result;
}

}  // namespace evr
