#!/usr/bin/env python3
"""Generate the local nakama rig's per-machine state (idempotent).

Writes tools/nakama-local/.state/ (git-ignored):
  nakama.yml       server config with freshly generated random keys (mode 600)
  certs/ca.pem     a throwaway CA that nakama is made to trust (SSL_CERT_FILE)
  certs/server.*   a cert for the Discord hostnames, served by discord_mock.py

Nothing here is a real secret and nothing is committed. Existing files are kept,
so rerunning never rotates keys under a running instance; `--force` regenerates.
"""

from __future__ import annotations

import argparse
import pathlib
import secrets
import subprocess
import sys

HERE = pathlib.Path(__file__).resolve().parent
STATE = HERE / ".state"
CERTS = STATE / "certs"

HOST_IP = "192.168.122.1"  # virbr0: where the Windows VM reaches this host
DISCORD_HOSTS = ["discord.com", "gateway.discord.gg", "discordapp.com", "cdn.discordapp.com"]

NAKAMA_YML = """\
# Generated by tools/nakama-local/setup.py. Local test instance; never used in production.
name: nevr-local
data_dir: /data

logger:
  stdout: true
  level: debug

database:
  address:
    - "postgres:localdb@postgres:5432/nakama"

socket:
  port: 7350
  server_key: {server_key}
  max_request_size_bytes: 2048000
  max_message_size_bytes: 2048000

session:
  token_expiry_sec: 7200
  encryption_key: {enc_key}
  refresh_encryption_key: {refresh_key}

runtime:
  http_key: {http_key}
  env:
    - "PLACEHOLDER_EMAIL_DOMAIN=null.echovrce.com"
    # Startup asks api.ipify.org for the external IP and fails without an answer; pin both.
    - "IP_ADDRESS_INTERNAL={host_ip}"
    - "IP_ADDRESS_EXTERNAL={host_ip}"
    # The fork refuses to start without a Discord bot; this token is fake and
    # discord_mock.py stands in for Discord (see its docstring).
    - "DISCORD_BOT_TOKEN=local-test-not-a-real-token"

console:
  port: 7351
  username: admin
  password: {console_password}
  signing_key: {signing_key}
"""


def run(*cmd: str) -> None:
    subprocess.run(cmd, check=True, capture_output=True)


def make_certs() -> None:
    CERTS.mkdir(parents=True, exist_ok=True)
    ca_key, ca_pem = CERTS / "ca.key", CERTS / "ca.pem"
    key, csr, pem, ext = CERTS / "server.key", CERTS / "server.csr", CERTS / "server.pem", CERTS / "san.ext"
    run("openssl", "req", "-x509", "-newkey", "rsa:2048", "-nodes", "-days", "3650", "-keyout", str(ca_key),
        "-out", str(ca_pem), "-subj", "/CN=nevr-local-test-ca")
    run("openssl", "req", "-newkey", "rsa:2048", "-nodes", "-keyout", str(key), "-out", str(csr),
        "-subj", "/CN=discord.com")
    ext.write_text("subjectAltName=" + ",".join(f"DNS:{h}" for h in DISCORD_HOSTS) + "\n")
    run("openssl", "x509", "-req", "-in", str(csr), "-CA", str(ca_pem), "-CAkey", str(ca_key), "-CAcreateserial",
        "-out", str(pem), "-days", "3650", "-extfile", str(ext))
    for f in (ca_key, key):
        f.chmod(0o600)
    for f in (csr, ext, CERTS / "ca.srl"):
        f.unlink(missing_ok=True)


def make_config() -> None:
    cfg = STATE / "nakama.yml"
    cfg.write_text(NAKAMA_YML.format(
        server_key=secrets.token_hex(16), enc_key=secrets.token_hex(16), refresh_key=secrets.token_hex(16),
        http_key=secrets.token_hex(16), host_ip=HOST_IP, console_password=secrets.token_hex(12), signing_key=secrets.token_hex(16)))
    cfg.chmod(0o600)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--force", action="store_true", help="regenerate keys and certs")
    args = ap.parse_args()
    STATE.mkdir(exist_ok=True)
    made = []
    if args.force or not (STATE / "nakama.yml").exists():
        make_config()
        made.append("nakama.yml")
    if args.force or not (CERTS / "server.pem").exists():
        make_certs()
        made.append("certs")
    print(f"state dir {STATE}: " + (", ".join(made) + " generated" if made else "already present, kept"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
