#include "scripting/script_stubs.h"

#include <string>
#include <vector>

namespace nevr_script {
namespace {

const char* LuauType(NevrValueType type) {
  switch (type) {
    case NEVR_VALUE_BOOL: return "boolean";
    case NEVR_VALUE_INT:
    case NEVR_VALUE_FLOAT: return "number";
    case NEVR_VALUE_STRING: return "string";
    default: return "never";
  }
}

// "test.add" -> "test_add": a type name part. Hook names are dotted names of
// [A-Za-z0-9_] (script_manifest.cpp ValidDottedName), so '.' is the only change.
std::string TypePart(const std::string& name) {
  std::string out = name;
  for (char& c : out) {
    if (c == '.') c = '_';
  }
  return out;
}

// A string literal type. Registered names are dotted names, so they need no escaping.
std::string Lit(const std::string& s) { return "\"" + s + "\""; }

// The intersection of `parts`, one per line; "never" when empty.
std::string Overloads(const std::vector<std::string>& parts, const char* indent) {
  if (parts.empty()) return "never";
  std::string out;
  for (size_t i = 0; i < parts.size(); ++i) {
    if (i > 0) out += std::string("\n") + indent + "& ";
    out += "(" + parts[i] + ")";
  }
  return out;
}

std::string CallType(const HookPoint& hook, NevrHookPhase phase) {
  const std::string name =
      std::string(phase == NEVR_HOOK_PRE ? "NevrPre_" : "NevrPost_") + TypePart(hook.Name());
  std::vector<std::string> gets, sets;
  for (const FieldSpec& f : hook.Fields()) {
    gets.push_back("(self: " + name + ", field: " + Lit(f.name) + ") -> " + LuauType(f.type));
    const bool writable = phase == NEVR_HOOK_PRE ? f.pre_writable : f.post_writable;
    if (writable) sets.push_back("(self: " + name + ", field: " + Lit(f.name) + ", value: " + LuauType(f.type) + ") -> ()");
  }
  std::string out = "-- " + hook.Name() + (phase == NEVR_HOOK_PRE ? ", before the call" : ", after the call") + "\n";
  out += "export type " + name + " = {\n";
  out += "    get: " + Overloads(gets, "        ") + ",\n";
  out += "    set: " + Overloads(sets, "        ") + ",\n";
  if (phase == NEVR_HOOK_PRE) out += "    skip: (self: " + name + ") -> (),\n";
  out += "}\n\n";
  return out;
}

}  // namespace

std::string GenerateLuauDefinitions(const Registry& registry) {
  std::string out =
      "-- Generated by nevr-runtime from its registered override points and hook points\n"
      "-- (src/scripting/script_stubs.cpp, host API v" + std::to_string(NEVR_HOST_API_VERSION) + "). Do not edit.\n\n";

  std::vector<std::string> overrides;
  for (const auto& point : registry.OverridePoints()) {
    overrides.push_back("(key: " + Lit(point.first) + ", value: " + LuauType(point.second) + ") -> (boolean?, string?)");
  }
  std::vector<std::string> hooks;
  for (const HookPoint* hook : registry.HookPoints()) {
    out += CallType(*hook, NEVR_HOOK_PRE);
    out += CallType(*hook, NEVR_HOOK_POST);
    const std::string part = TypePart(hook->Name());
    hooks.push_back("(name: " + Lit(hook->Name()) + ", callbacks: { pre: ((h: NevrPre_" + part +
                    ") -> ())?, post: ((h: NevrPost_" + part + ") -> ())? }) -> (boolean?, string?)");
  }

  out += "declare nevr: {\n";
  out += "    override: " + Overloads(overrides, "        ") + ",\n";
  out += "    hook: " + Overloads(hooks, "        ") + ",\n";
  out += "    log: (level: \"debug\" | \"info\" | \"warn\" | \"error\", message: string) -> (),\n";
  out += "}\n";
  return out;
}

}  // namespace nevr_script
