// AUTO-GENERATED by tools/gen_symbol_corpus.py — DO NOT EDIT BY HAND.
// Re-run the generator when the game binary is updated to refresh the string pool.
//
// Maps uint64_t symbol hash values to human-readable names.
// Two hash pipelines are supported:
//   1. CSymbol64 (CRC64 with polynomial 0x95ac9329ac4bc9b5) — resource / level names
//   2. CMatSym::Hash + SMatSymData::HashA — SNS messages, NRadGame events
//
// LookupSymbolName() searches both tables and returns the first match.

#pragma once

#include <cstdint>

namespace EchoVR {

/// Look up a symbol name by its 64-bit hash value.
/// Returns the name string if found, or nullptr if unknown.
/// The caller should format a hex fallback when nullptr is returned.
const char* LookupSymbolName(uint64_t hash);

/// Format a symbol ID for display.
/// Writes at most maxLen bytes (including null terminator) to buf.
/// If the hash is known, writes the name; otherwise writes the hex value.
/// Returns the number of bytes that would have been written (excluding null).
int FormatSymbolId(char* buf, int maxLen, uint64_t hash);

}  // namespace EchoVR
