#!/usr/bin/env python3
"""Writes src/quest/diag/hwdump_vk_fields.inc: every member of VkPhysicalDeviceLimits and
VkPhysicalDeviceFeatures, read from the NDK's vulkan_core.h, as X-macro lists for the hardware dump (#335).

usage: tools/gen_hwdump_vk_fields.py <path to vulkan_core.h> <output .inc>
"""
from __future__ import annotations

import re
import sys


def members(src: str, name: str) -> list[tuple[str, str, str | None]]:
    m = re.search(r"typedef struct " + name + r" \{(.*?)\} " + name + ";", src, re.S)
    if m is None:
        sys.exit(f"gen_hwdump_vk_fields: struct {name} not found")
    out = []
    for line in m.group(1).strip().splitlines():
        line = line.strip().rstrip(";")
        mm = re.match(r"(\w+)\s+(\w+)(\[(\d+)\])?$", line)
        if mm is None:
            sys.exit(f"gen_hwdump_vk_fields: cannot parse member line {line!r} of {name}")
        out.append((mm.group(1), mm.group(2), mm.group(4)))
    return out


def main() -> None:
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    src = open(sys.argv[1], encoding="utf-8").read()
    limits = members(src, "VkPhysicalDeviceLimits")
    features = members(src, "VkPhysicalDeviceFeatures")
    lines = [
        "// Generated by tools/gen_hwdump_vk_fields.py from the NDK's vulkan_core.h; do not edit.",
        f"// VkPhysicalDeviceLimits: {len(limits)} members. VkPhysicalDeviceFeatures: {len(features)} members.",
        "#define NEVR_HWDUMP_VK_LIMITS(X, XA) \\",
    ]
    for i, (_, name, count) in enumerate(limits):
        tail = " \\" if i + 1 < len(limits) else ""
        lines.append(f"  XA({name}, {count}){tail}" if count else f"  X({name}){tail}")
    lines.append("#define NEVR_HWDUMP_VK_FEATURES(X) \\")
    for i, (_, name, _) in enumerate(features):
        tail = " \\" if i + 1 < len(features) else ""
        lines.append(f"  X({name}){tail}")
    open(sys.argv[2], "w", encoding="utf-8").write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
