#!/usr/bin/env bash
set -euo pipefail

# Generates src/runtime/log/symcache_data.cpp from the nakama EVR symbol cache.
# Reads the Go map literal from the evrcat vendor directory and emits a C++ array
# of {uint64_t hash, const char* name} pairs, sorted by hash.

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
go_file="/home/andrew/src/evrcat/vendor/github.com/heroiclabs/nakama/v3/server/evr/core_hash_lookup.go"
out="$repo_root/src/runtime/log/symcache_data.cpp"

if [[ ! -f "$go_file" ]]; then
    echo "generate-symcache.sh: ERROR — Go symbol cache not found: $go_file" >&2
    echo "Is the evrcat vendor tree present at /home/andrew/src/evrcat?" >&2
    exit 1
fi

entries_file=$(mktemp)
scratch=$(mktemp)
trap 'rm -f "$entries_file" "$scratch"' EXIT

# Extract lines 33-9107 (the map body) and filter for entry lines
sed -n '33,9107p' "$go_file" | grep -E '^\s*0x[0-9a-fA-F]{16}:' > "$entries_file"

count=$(wc -l < "$entries_file")
echo "generate-symcache.sh: extracting $count entries from core_hash_lookup.go" >&2

if [[ "$count" -lt 1000 ]]; then
    echo "generate-symcache.sh: ERROR — only $count entries extracted, expected 9000+." >&2
    echo "The Go file format may have changed. Check the grep/regex." >&2
    exit 1
fi

# Transform each line into two tab-separated fields: hashULL\tvalue (no quotes on value).
# Input:  \t0xc8c33e482f601dbe: "uscn",
# Output: 0xc8c33e482f601dbeULL\tuscn
#
# Uses awk -F'"' to split on double-quotes: $1 is hash prefix, $2 is the string value.
# gsub escapes any backslash or double-quote that appears WITHIN the value.
# The intermediate format is tab-delimited with NO quotes on the value field, so
# the sort + final formatting pass can add exactly one layer of C-string quotes.
awk -F'"' '{
    hash = $1;
    gsub(/[[:space:]:]/, "", hash);
    name = $2;
    gsub(/\\/, "\\\\", name);
    gsub(/"/, "\\\"", name);
    printf "%sULL\t%s\n", hash, name;
}' "$entries_file" | sort -t$'\t' -k1,1n > "$scratch"

# Generate the output file
{
    echo '// AUTO-GENERATED by tools/generate-symcache.sh — DO NOT EDIT'
    echo '// Source: evrcat vendor (nakama EVR symbol cache)'
    echo ''
    echo '#include "runtime/log/symcache.h"'
    echo ''
    echo 'namespace evr {'
    echo ''
    echo "// Total entries: $count"
    echo ''
    echo 'extern const SymCacheEntry kSymCacheData[] = {'

    # Final formatting: split on tab, wrap value in C-string quotes
    awk -F'\t' '{ printf "    {%s, \"%s\"},\n", $1, $2; }' "$scratch"

    echo '};'
    echo ''
    echo "extern const int kSymCacheCount = $count;"
    echo ''
    echo '}  // namespace evr'
} > "$out"

echo "generate-symcache.sh: wrote $count entries to $out" >&2
